model:
  name: 'MinkUNet34'
  in_feat_size: 1
  out_classes: 10

dataset:
  version: 'v1.0-trainval'
  name: 'NuScenes'
  dataset_path: '/home/lamiaeel/scratch/data/NuScenes'
  mapping_path: '_resources/nuscenes_semantickitti.yaml'
  target: 'SemanticKITTI'
  voxel_size: 0.1
  num_pts: 50000
  ignore_label: -1
  augment_data: true


pipeline:
  epochs: 100
  steps: null
  gpus: [0]
  precision: 32
  loss: 'SoftDICELoss'
  seed: 1234
  save_dir: 'experiments/pretrained'
  validate_target: true

  dataloader:
    batch_size: 1
    num_workers: 16

  optimizer:
    name: 'SGD'
    lr: 0.001

  scheduler:
    name: 'ExponentialLR'

  lightning:
    check_val_every_n_epoch: 5
    clear_cache_int: 1
    resume_checkpoint: null
    val_check_interval: 1.0
    num_sanity_val_steps: 0


  wandb:
    offline: true
